<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SMACompanyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('sma_companies')->truncate();

        //customer
        DB::table('sma_companies')->insert([
            'id' => 1,
            'group_id' => 3,
            'group_name' => 'customer',
            'customer_group_id' => 1,
            'customer_group_name' => 'General',
            'name' => 'Walk-in Customer',
            'company' => 'Walk-in Customer',
            'vat_no' => '',
            'address' => 'Customer Address',
            'city' => 'Colombo',
            'state' => 'Western',
            'postal_code' => '10100',
            'country' => 'Sri Lanka',
            'phone' => '94717107025',
            'email' => 'customer@orions360.com',
            'cf1' => '',
            'cf2' => '',
            'cf3' => '',
            'cf4' => '',
            'cf5' => '',
            'cf6' => '',
            'invoice_footer' => NULL,
            'payment_term' => 0,
            'logo' => 'logo.png',
            'award_points' => 0,
        ]);
        //supplier
        DB::table('sma_companies')->insert([
            'id' => 2,
            'group_id' => 4,
            'group_name' => 'supplier',
            'customer_group_id' => NULL,
            'customer_group_name' => NULL,
            'name' => 'Test Supplier',
            'company' => 'Supplier Company Name',
            'vat_no' => NULL,
            'address' => 'Supplier Address',
            'city' => 'Colombo',
            'state' => 'Western',
            'postal_code' => '10150',
            'country' => 'Sri Lanka',
            'phone' => '94717107025',
            'email' => 'supplier@orions360.com',
            'cf1' => '',
            'cf2' => '',
            'cf3' => '',
            'cf4' => '',
            'cf5' => '',
            'cf6' => '',
            'invoice_footer' => NULL,
            'payment_term' => 0,
            'logo' => 'logo.png',
            'award_points' => 0,
        ]);

        //billing company
        DB::table('sma_companies')->insert([
            'id' => 3,
            'group_id' => NULL,
            'group_name' => 'biller',
            'customer_group_id' => NULL,
            'customer_group_name' => NULL,
            'name' => 'Orions360',
            'company' => 'Orions360.com',
            'vat_no' => 5555,
            'address' => 'Biller Address',
            'city' => 'Calgary',
            'state' => 'Alberta',
            'postal_code' => '10150',
            'country' => 'Canada',
            'phone' => '94717107025',
            'email' => 'info@orions360.com',
            'cf1' => '',
            'cf2' => '',
            'cf3' => '',
            'cf4' => '',
            'cf5' => '',
            'cf6' => '',
            'invoice_footer' => ' Thank you for shopping with us. Please come again',
            'payment_term' => 0,
            'logo' => 'logo.png',
            'award_points' => 0,
        ]);

        /*DB::table('sma_companies')->insert([
            'id' => 4,
            'group_id' => 4,
            'group_name' => 'supplier',
            'customer_group_id' => NULL,
            'customer_group_name' => NULL,
            'name' => 'A R MARKETING CASTROL AMW',
            'company' => 'A R MARKETING CASTROL AMW',
            'vat_no' => NULL,
            'address' => 'Supplier Address',
            'city' => 'Colombo',
            'state' => 'Western',
            'postal_code' => '10150',
            'country' => 'Sri Lanka',
            'phone' => '94717107025',
            'email' => 'supplier@orions360.com',
            'cf1' => '',
            'cf2' => '',
            'cf3' => '',
            'cf4' => '',
            'cf5' => '',
            'cf6' => '',
            'invoice_footer' => NULL,
            'payment_term' => 0,
            'logo' => 'logo.png',
            'award_points' => 0,
        ]);
        DB::table('sma_companies')->insert([
            'id' => 5,
            'group_id' => 4,
            'group_name' => 'supplier',
            'customer_group_id' => NULL,
            'customer_group_name' => NULL,
            'name' => 'ABEYWEERA COMPANY',
            'company' => 'ABEYWEERA COMPANY',
            'vat_no' => NULL,
            'address' => 'Supplier Address',
            'city' => 'Colombo',
            'state' => 'Western',
            'postal_code' => '10150',
            'country' => 'Sri Lanka',
            'phone' => '94717107025',
            'email' => 'supplier@orions360.com',
            'cf1' => '',
            'cf2' => '',
            'cf3' => '',
            'cf4' => '',
            'cf5' => '',
            'cf6' => '',
            'invoice_footer' => NULL,
            'payment_term' => 0,
            'logo' => 'logo.png',
            'award_points' => 0,
        ]);
        DB::table('sma_companies')->insert([
            'id' => 6,
            'group_id' => 4,
            'group_name' => 'supplier',
            'customer_group_id' => NULL,
            'customer_group_name' => NULL,
            'name' => 'AMW SUZUKI',
            'company' => 'AMW SUZUKI',
            'vat_no' => NULL,
            'address' => 'Supplier Address',
            'city' => 'Colombo',
            'state' => 'Western',
            'postal_code' => '10150',
            'country' => 'Sri Lanka',
            'phone' => '94717107025',
            'email' => 'supplier@orions360.com',
            'cf1' => '',
            'cf2' => '',
            'cf3' => '',
            'cf4' => '',
            'cf5' => '',
            'cf6' => '',
            'invoice_footer' => NULL,
            'payment_term' => 0,
            'logo' => 'logo.png',
            'award_points' => 0,
        ]);
        DB::table('sma_companies')->insert([
            'id' => 7,
            'group_id' => 4,
            'group_name' => 'supplier',
            'customer_group_id' => NULL,
            'customer_group_name' => NULL,
            'name' => 'HALFORD CARE',
            'company' => 'HALFORD CARE',
            'vat_no' => NULL,
            'address' => 'Supplier Address',
            'city' => 'Colombo',
            'state' => 'Western',
            'postal_code' => '10150',
            'country' => 'Sri Lanka',
            'phone' => '94717107025',
            'email' => 'supplier@orions360.com',
            'cf1' => '',
            'cf2' => '',
            'cf3' => '',
            'cf4' => '',
            'cf5' => '',
            'cf6' => '',
            'invoice_footer' => NULL,
            'payment_term' => 0,
            'logo' => 'logo.png',
            'award_points' => 0,
        ]);*/

    }
}
