<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SMASettingTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sma_settings')->truncate();

        DB::table('sma_settings')->insert([
            'setting_id' => 1,
            'logo' => 'logo2.png',
            'logo2' => 'logo3.png',
            'site_name' => 'Orions360 POS',
            'language' => 'english',
            'default_warehouse' => 1,
            'accounting_method' => 0,
            'default_currency' => 'USD',
            'default_tax_rate' => 1,
            'rows_per_page' => 10,
            'version' => '3.4.47',
            'default_tax_rate2' => 1,
            'dateformat' => 5,
            'sales_prefix' => 'SALE',
            'quote_prefix' => 'QUOTE',
            'purchase_prefix' => 'PO',
            'transfer_prefix' => 'TR',
            'delivery_prefix' => 'DO',
            'payment_prefix' => 'IPAY',
            'return_prefix' => 'SR',
            'returnp_prefix' => 'PR',
            'expense_prefix' => NULL,
            'item_addition' => 0,
            'theme' => 'default',
            'product_serial' => 1,
            'default_discount' => 1,
            'product_discount' => 1,
            'discount_method' => 1,
            'tax1' => 1,
            'tax2' => 1,
            'overselling' => 0,
            'restrict_user' => 1,
            'restrict_calendar' => 0,
            'timezone' => 'Asia/Colombo',
            'iwidth' => 800,
            'iheight' => 800,
            'twidth' => 150,
            'theight' => 150,
            'watermark' => 0,
            'reg_ver' => 0,
            'allow_reg' => 0,
            'reg_notification' => 0,
            'auto_reg' => NULL,
            'protocol' => 'mail',
            'mailpath' => '/usr/sbin/sendmail',
            'smtp_host' => 'smtp.zoho.com',
            'smtp_user' => 'info@orions360.com',
            'smtp_pass' => 'iUG3n3Z0UEpX',
            'smtp_port' => '587',
            'smtp_crypto' => NULL,
            'corn' => NULL,
            'customer_group' => 1,
            'default_email' => 'info@orions360.com',
            'mmode' => 0,
            'bc_fix' => 4,
            'auto_detect_barcode' => 1,
            'captcha' => 0,
            'reference_format' => 2,
            'racks' => 1,
            'attributes' => 1,
            'product_expiry' => 0,
            'decimals' => 2,
            'qty_decimals' => 2,
            'decimals_sep' => '.',
            'thousands_sep' => ',',
            'invoice_view' => 0,
            'default_biller' => 3,
            'envato_username' => 'dinesh92',
            'purchase_code' => 'ade4ac6f-e9b4-4413-85d9-c3d21710053e',
            'rtl' => 0,
            'each_spent' => NULL,
            'ca_point' => NULL,
            'each_sale' => NULL,
            'sa_point' => NULL,
            'update' => 0,
            'sac' => 0,
            'display_all_products' => 0,
            'display_symbol' => NULL,
            'symbol' => NULL,
            'remove_expired' => 0,
            'barcode_separator' => '-',
            'set_focus' => 0,
            'price_group' => NULL,
            'barcode_img' => 1,
            'ppayment_prefix' => 'POP',
            'disable_editing' => 90,
            'qa_prefix' => NULL,
            'update_cost' => NULL,
            'apis' => 0,
            'state' => NULL,
            'pdf_lib' => 'dompdf',
            'use_code_for_slug' => NULL,
            'ws_barcode_type' => 'weight',
            'ws_barcode_chars' => NULL,
            'flag_chars' => NULL,
            'item_code_start' => NULL,
            'item_code_chars' => NULL,
            'price_start' => NULL,
            'price_chars' => NULL,
            'price_divide_by' => NULL,
            'weight_start' => NULL,
            'weight_chars' => NULL,
            'weight_divide_by' => NULL,
        ]);
    }
}
